### ISSUE TITLE
Missing dependency on `@bufbuild/protobuf` after ts-proto upgrade

### ISSUE THREAD

**Issue by sybereal** [deeplay-io/nice-grpc#761]
#709 upgraded from ts-proto v1 to v2. As noted at the top of the ts-proto README, this involved a migration from `protobufjs` to `@bufbuild/protobuf`. Presumably due to ts-proto itself depending on `@bufbuild/protobuf`, thus ensuring it's installed, this did not cause any error in this repo's CI.

However, since ts-proto is only a devDependency in nice-grpc packages, the dependency on ts-proto and thus `@bufbuild/protobuf` does not propagate to nice-grpc users. Upgrading to a version that includes #709 therefore greets the user with errors similar to the following (slightly different depending on build tool and packages used; this is esbuild):

```
Error: Build failed with 5 errors:
node_modules/.pnpm/nice-grpc-error-details@0.2.9/node_modules/nice-grpc-error-details/lib/proto/google/protobuf/any.js:10:23: ERROR: Could not resolve "@bufbuild/protobuf/wire"
node_modules/.pnpm/nice-grpc-error-details@0.2.9/node_modules/nice-grpc-error-details/lib/proto/google/protobuf/duration.js:10:23: ERROR: Could not resolve "@bufbuild/protobuf/wire"
node_modules/.pnpm/nice-grpc-error-details@0.2.9/node_modules/nice-grpc-error-details/lib/proto/google/rpc/error_details.js:10:23: ERROR: Could not resolve "@bufbuild/protobuf/wire"
node_modules/.pnpm/nice-grpc-error-details@0.2.9/node_modules/nice-grpc-error-details/lib/proto/google/rpc/status.js:10:23: ERROR: Could not resolve "@bufbuild/protobuf/wire"
node_modules/.pnpm/nice-grpc-server-health@2.0.14/node_modules/nice-grpc-server-health/lib/proto/grpc/health/v1/health.js:10:23: ERROR: Could not resolve "@bufbuild/protobuf/wire"
```

The issue can be worked around by manually adding a dependency on `@bufbuild/protobuf` to a project, or using a mechanism like pnpm's `packageExtension` to patch the dependencies list of affected packages, but this is clearly not the intended state. For example, this is what we had to add to our `pnpm-workspace.yaml` to fix our builds after upgrade nice-grpc-server-health to 2.0.14 and nice-grpc-error-details to 0.2.9, respectively.

```yml
packageExtensions:
  nice-grpc-error-details@0.2.9:
    dependencies:
      "@bufbuild/protobuf": "^2.0.0"
  nice-grpc-server-health@2.0.14:
    dependencies:
      "@bufbuild/protobuf": "^2.0.0"
```

**Comment by aikoven** [comment]
Thank you for the report!

I have fixed the missing dependency and published updated packages.

```
 - nice-grpc-error-details@0.2.10
 - nice-grpc-server-health@2.0.15
```
